name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run lint
      - run: npm run build:ts
      - name: Build and synth CDK
        working-directory: ./cdk
        run: |
          npm ci
          npm run lint
          npm run test
          npm run synth


